myNewFile = open("new.txt","wb")
print ("Name of the file: ", myNewFile.name)
print ("Closed or not : ", myNewFile.closed)
print ("Opening mode : ", myNewFile.mode)
#print ("Reading the file: ", myNewFile.read())
print ("Reading the file: ", myNewFile.write(b'\x07\x08\x07'))
myNewFile.close()
myNewFile = open("new.txt","r")
print ("Reading the file: ", myNewFile.read())